package vs.forum.entity;

public enum Permission {

	ADMIN_MANAGE_ACCESS, ADMIN_MODIFY_PERMISSIONS, ADMIN_CHANGE_GROUP, ADMIN_SUSPEND_USER, ADMIN_DEACTIVATE_USER,
	ADMIN_TOPIC, MODERATOR_UPDATE_COMMENT, MODERATOR_DELETE_COMMENT, MEMBER_CREATE_COMMENT, MEMBER_UPDATE_COMMENT,
	MEMBER_DELETE_COMMENT;

}
